### ISSUE TITLE
radius alpha beta gamma

### ISSUE THREAD

**Issue by fabio1999ita** [dm94/DarkBot-Modules#2]
the radius doesen't work in alpha beta gamma whit kristallon (the bot dies).
same thing in the corner the bot does not keep a correct distance and gets hit

**Comment by Teals53** [comment]
and usually bot go outside raidus so cant attack just escaping

**Comment by djalex9** [comment]
Greetings, thanks for your work, the module does not prioritize the NPCs, for example the Devourer, I set them to 100, and the others that are around -100, but still always attacks the Devourer

**Comment by Teals53** [comment]
if u select zeta gate from gg settings bot not attack devourer firstly

**Comment by fabio1999ita** [comment]
> and usually bot go outside raidus so cant attack just escaping

the bot escapes to take shelter ...

**Comment by Teals53** [comment]
so always escape and never done gate ? yes really good idea

**Comment by fabio1999ita** [comment]
> so always escape and never done gate ? yes really good idea

i don't try new version, in "v1 Beta 21" the bot escape only for repair

**Comment by djalex9** [comment]
> if u select zeta gate from gg settings bot not attack devourer firstly

if I have selected from the module the gg zeta, maybe it's because I'm using the 21

**Comment by Teals53** [comment]
Use latest

**Comment by fabio1999ita** [comment]
so in the last version radius for alpha beta gamma is fix? when there are kristallon and in the corner?

**Comment by Teals53** [comment]
nope i tested today and my ship still deading from corner kristallin in beta xD

**Comment by fabio1999ita** [comment]
new range for abg works
